
package test;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestWS", targetNamespace = "http://test.wx.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWS {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://test.wx.com/", className = "test.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://test.wx.com/", className = "test.TestResponse")
    @Action(input = "http://test.wx.com/TestWS/testRequest", output = "http://test.wx.com/TestWS/testResponse")
    public String test();

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<test.AdminUsr>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readTest", targetNamespace = "http://test.wx.com/", className = "test.ReadTest")
    @ResponseWrapper(localName = "readTestResponse", targetNamespace = "http://test.wx.com/", className = "test.ReadTestResponse")
    @Action(input = "http://test.wx.com/TestWS/readTestRequest", output = "http://test.wx.com/TestWS/readTestResponse")
    public List<AdminUsr> readTest(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "writeTest", targetNamespace = "http://test.wx.com/", className = "test.WriteTest")
    @ResponseWrapper(localName = "writeTestResponse", targetNamespace = "http://test.wx.com/", className = "test.WriteTestResponse")
    @Action(input = "http://test.wx.com/TestWS/writeTestRequest", output = "http://test.wx.com/TestWS/writeTestResponse")
    public String writeTest();

}
